import { v4 as uuid } from 'uuid';

export const data = [
  {
    value: 'regions',
    NAME: 'showRegions',
    id: uuid(),
    name: 'block__regions',
    array: [
      {
        id: uuid(),
        src: './images/maldives.png',
        alt: 'Maldives',
        country: 'Maldives',
      },

      {
        id: uuid(),
        src: './images/spain.png',
        alt: 'Spain',
        country: 'Spain',
      },
      {
        id: uuid(),
        src: './images/norway.png',
        alt: 'Norway',
        country: 'Norway',
      },
      {
        id: uuid(),
        src: './images/island.png',
        alt: 'Island',
        country: 'Island',
      },
      {
        id: uuid(),
        src: './images/japan.png',
        alt: 'Japan',
        country: 'Japan',
      },
      {
        id: uuid(),
        src: './images/france.png',
        alt: 'France',
        country: 'France',
      },
      {
        id: uuid(),
        src: './images/scotland.png',
        alt: 'Scotland',
        country: 'Scotland',
      },
      {
        id: uuid(),
        src: './images/russia.png',
        alt: 'Russia',
        country: 'Russia',
      },
    ],
  },
  {
    value: 'cities',
    NAME: 'showCities',
    id: uuid(),
    name: 'block__cities',
    array: [
      {
        id: uuid(),
        src: './images/berlin.png',
        alt: 'Berlin',
        city: 'Berlin,',
        country: 'Germany,',
      },

      {
        id: uuid(),
        src: './images/paris.png',
        alt: 'Paris',
        city: 'Paris,',
        country: 'France',
      },
      {
        id: uuid(),
        src: './images/budapest.png',
        alt: 'Budapest',
        city: 'Budapest,',
        country: 'Hungary',
      },
      {
        id: uuid(),
        src: './images/london.png',
        alt: 'London',
        city: 'London,',
        country: 'United Kingdom',
      },
      {
        id: uuid(),
        src: './images/barcelona.png',
        alt: 'Barcelona',
        city: 'Barcelona,',
        country: 'Spain',
      },
      {
        id: uuid(),
        src: './images/tbilisi.png',
        alt: 'Tbilisi',
        city: 'Tbilisi,',
        country: 'Georgia',
      },
      {
        id: uuid(),
        src: './images/moscow.png',
        alt: 'Moscow',
        city: 'Moscow,',
        country: 'Russia',
      },
      {
        id: uuid(),
        src: './images/amsterdam.png',
        alt: 'Amsterdam',
        city: 'Amsterdam,',
        country: 'Netherlands',
      },
    ],
  },
  {
    value: 'places',
    NAME: 'showPlaces',
    id: uuid(),
    name: 'block__places',
    array: [
      {
        id: uuid(),
        src: './images/ed_castle.png',
        alt: 'Edinburgh Castle',
        city: 'Edinburgh,',
        country: 'United Kingdom',
        dest: 'Edinburgh Castle,',
      },

      {
        id: uuid(),
        src: './images/neuschwanstein.png',
        alt: 'Neuschwanstein',
        city: 'Fussen',
        country: 'Germany',
        dest: 'Neuschwanstein',
      },
      {
        id: uuid(),
        src: './images/big_ban.png',
        alt: 'Big Ban,',
        city: 'London',
        country: 'United Kingdom',
        dest: 'Big Ben,',
      },
      {
        id: uuid(),
        src: './images/colosseum.png',
        alt: 'Colosseum',
        city: 'Roma,',
        country: 'Italy',
        dest: 'Colosseum,',
      },
      {
        id: uuid(),
        src: './images/matterhom.png',
        alt: 'Matterhom',
        city: 'Zermatt,',
        country: 'Switzerland',
        dest: 'Matterhom,',
      },
      {
        id: uuid(),
        src: './images/morskie_oko.png',
        alt: 'Morskie_oko',
        city: '',
        country: 'Poland',
        dest: 'Morskie oko,',
      },
      {
        id: uuid(),
        src: './images/krka.png',
        alt: 'Krka',
        city: '',
        country: 'Croatia',
        dest: 'Krka,',
      },
      {
        id: uuid(),
        src: './images/cabo_da_roca.png',
        alt: 'Cabo da roca',
        city: 'Sintra,',
        country: 'Portugal',
        dest: 'Cabo da roca,',
      },
    ],
  },
];
